POST {{base_url}}/task/create
Authorization: Bearer {{access_token}}
Content-Type: application/json

{
  "project_id": 1,
  "name": "Tasks",
  "description": "Desc Task",
  "status": "PLANNING"
}
###
